### ISSUE TITLE
Editor: Update shared axis across maps

### ISSUE THREAD

**Issue by GTO2013** [RomRaider/RomRaider#115]
When you change the axis on one map, it doesn't show those updates on other maps you open.
Eg ign1 & fuel1 both have the same rpm axis. If I change the rpm axis values in ign1, those changes aren't shown in fuel1 until I save the file and reload in RR.

**Comment by dschultzca** [comment]
When the Editor creates its representation of a map, it creates a 1D table for the axis (x or y).  These 1D axis tables are not shared amongst the maps in the Editor, therefore changing one common axis table will  not change the underlying data of other maps that share the same data within the ROM.  To change the common axis in the Editor, the very last map in the map tree must have its axis changed, saved, ROM closed and reload.  All maps will then reflect the change.  Then all maps using the common axis must be rescaled to account for the change, or unexpected vehicle operation may occur.

**Comment by GTO2013** [comment]
What do you think of the following idea: Currently the ROM is parsed and each table then saves the binary raw values as a double in DataCells. When the ROM is saved all tables are saved into the ROM to update. Wouldnt it be better to pass the raw byte array (which is already available in the ROM object) to all the generated tables and let them update the raw byte array immediately once you make a change? Then you just have to call populateTable on all open tables and the next table you open should already reflect the change. Saving the file is then just writing the byte array from the ROM object, which already contains all changes.

**Comment by dschultzca** [comment]
I had tried to tackle this problem a few years ago.  My approach was to check the axis table parameters and if a table already existed with the same parameters, then assign the current axis table object to the new 2D or 3D table.  I quickly found that the approach did not work well with the various table utility functions for compare, undo, copy etc.  Since it's been a few years I don't think I have the modifications I made anymore.  It was working out to be a large effort.  I'm not sure how your approach may work, you'd need to try and then validate all the table functions.

As for the ramOffset, I believe this is for 16bit Subaru ECU ROMs where two different sizes are supported.  Either a 160kB or a 192kB file would represent the ECU image.  The difference between the two is the 32kB hole in the middle where the ECU RAM is mapped.  The ramOffest I believe, is used when opening the 160kB file and the offset accounts for the mapped space.  I think it comes into play since all addresses are in reference to the 192kB image and need to subtract the offset from the storageAddress when reading the data from the 160kB file.
