### ISSUE TITLE
Beta Editor - Bitwise Switch Size Limit

### ISSUE THREAD

**Issue by Pytrex** [RomRaider/RomRaider#133]
This is in reference to the current build on GitHub. So it appears that bitwise switches no longer support anything longer than a single byte. It throws the error specified in the pic below IF you remove the sizey attribute. If you retain the sizey attribute, it'll load, but then throw a blank error upon attempting to refresh. 
![RRError](https://user-images.githubusercontent.com/13327710/135647999-ccd02435-2819-4023-96e8-8dc7aecc4cdc.PNG)

**Comment by GTO2013** [comment]
I fixed some things regarding the Bitwise Switch, but I could not replicate your exact issue. I am currently developing on https://github.com/GTO2013/RomRaider/tree/set_fix, can you try to build this and check if the issue is still there? If yes, please upload the definition and the binary you used, thanks!

**Comment by Pytrex** [comment]
That seems to have fixed it, thanks! :)
