### ISSUE TITLE
Editor - scalingbase does not work with table multi-scalings

### ISSUE THREAD

**Issue by dschultzca** [RomRaider/RomRaider#137]
For RomRaider versions: since 0.5.8 RC1

When support for multi-scaling options in a table was added, the 'name' attribute was used to identify the scaling entries as different, for example:
`<scaling name="Metric" units="Bar absolute" expression="x*.001333224" to_byte="x/.001333224" format="#0.000"/>`
`<scaling name="Standard" units="psi relative sea level" expression="(x-760)*.01933677" to_byte="(x/.01933677)+760" format="0.00"/>
`
This reuse of the 'name' attribute interferes with the scalingbase feature.

We need an attribute other than 'name' to identify the scale element units that is compatible with scalingbase.
Suggestions:
'measure'
'sou' == System of Units
'mou' == Measure of Units

This doesn't appear to be an issue if a table only has a single scale element defined, but the <scalingbase format= attribute is overwritten when the <scale base="xyz" does not contain a format attribute, the default is applied from: https://github.com/RomRaider/RomRaider/blob/425c8e01d9826f1a6ad519500b35d92f12d38cf8/src/main/java/com/romraider/xml/TableScaleUnmarshaller.java#L381
https://www.romraider.com/forum/viewtopic.php?p=3166#p3166

When the unmarshallScale method is inheriting from a existing scalingbase it should not overwrite any attribute value if no attributes are specified in the table's <scale> entry.
Example: if  table scale is `<scale base="xyz" />` then none of the inherited base attributes should be changed (see the displayed difference in boost table A & B in the attached).

Test definition attached for [ROM A2WC522S](http://www.romraider.com/forum/download/file.php?id=5114).
[scalingbase.zip](https://github.com/RomRaider/RomRaider/files/7272199/scalingbase.zip)

**Comment by GTO2013** [comment]
Why is the scalingbase attribute needed actually? If you create a table which inherits from a base table which has a scale defined, what happens with the scale in the base table? Is it not inherited in that case? Because somebody asked me something similar recently.

**Comment by Pytrex** [comment]
> Why is the scalingbase attribute needed actually? If you create a table which inherits from a base table which has a scale defined, what happens with the scale in the base table? Is it not inherited in that case? 

Not sure on how base tables operate (Dschultz actually just recently taught me scalingbase haha), but it's much easier to have a scalingbase attribute over having to rely on table scalings. Reason being is that with the scalingbase attribute, they're completely separate from the rest of the definition files (they're located in the header). So if you want to modify any of the scalings, you would be able to do so with ease. If your scalings are all referencing a base table, then you'd have to jump around the definition file to get to said base tables before being able to make changes to the scaling data. 

I can confirm that with my massive definition template, it's much easier working with the scalingbase than having individual scalings. The one thing I haven't tested is whether you can overwrite scaling attributes on a specific table WITHOUT overwriting that attribute on the vector table (or however the scalings are stored). Because if so, that would definitely be pretty cool.

**Comment by dschultzca** [comment]
In addition to the above info, scalingbase works just like base table inheritance.
If you have say 100 base tables that have an RPM axis you can define the scaling for all those tables in one scalingbase element.  Then in the base table `<scale>` element your refer to the scalingbase by its `name` attribute (`base="nameX"`).
If you need to change any attribute of a scalingbase when inherited into a table you can override that attribute in the base table's `<scale>` element. For example to change the displayed number format `<scale base="nameX" format="#.00" />`

To support different scalings for a single table such as Metric, SI, Imperial, multiple `<scale>` elements can be defined in the base table.  But here there is a conflict in the `name` attribute.

I can take on fixing this issue if you'd like.

**Comment by GTO2013** [comment]
I see, thanks for the explanation! Would iterating over the existing attributes help with this? Instead of unmarshallAttribute(node, name, default) it could use tableNode.getAttributes().item(i) in a loop to only set values which are actually defined. You would have to make sure that the defaults in the Table classes are setup properly in this case though. But you also wouldnt have to define defaults twice in the code.

Additionally, wouldnt it be more efficient if something like this was possible?

```
<table type="3D" name="Ignition Retard" >
	<scaling ... />
	<table type="X Axis" ...> </table>
	<table type="Y Axis" name="Engine Speed"/>
</table> 

<table type="2D" name="Fuel Table" >
	<scaling ... />
	<table type="X Axis" name="Engine Speed"/>
	<table type="Y Axis" ... />
</table>

<table type="Axis" name="Engine Speed" storagetype="uint8" logparam="P8" sizey="x" >
    <scaling units="RPM" expression="x*32" to_byte="x/32" format="0" fineincrement="30" coarseincrement="300" />
</table>
```

So you can define an axis outside of a table, which does not get rendered, but can get referenced by name when its needed? You could make the definitions a lot more compact that way.

**Comment by Pytrex** [comment]
> So you can define an axis outside of a table, which does not get rendered, but can get referenced by name when its needed? You could make the definitions a lot more compact that way.

Funny enough, I was just thinking about that! Given the fact that many axes share the same scaling data, I don't see any drawback to having the table data stored separately. You could just store them with the scalings in the header I think. The one thing I'd like changed if it went that route would be having the axis title be just the units or have a separate way of identifying different tables. Because currently, "Engine Speed (RPM)" as a unit in a "Engine Speed (RPM)" table name yields the following axis title "Engine Speed (RPM)(Engine Speed (RPM))". Currently, my scaling bases are named based off the scaling data (expression x*2 for degrees means the scalingbase name="Degrees (x*2)") and this isn't an issue because it just shows "Default" in the scaling selector. But with axis titles, it's a different story. 

So if the axes were to be separated, it would be nice to have maybe a "displayname" attribute as well.

**Comment by dschultzca** [comment]
You can support whatever combination of base and inheritance you wish, but it must all be backwards compatible with existing definitions.  How much coding time do you have? ;-)

There's already a way to create a new table (not an axis) based from an existing table, by using the `base` attribute in the new table and defining a new `name` (and other elements) for it.
```
  <table type="3D" name="Target Boost A" category="Boost Control - Target" storagetype="uint16" endian="big" sizex="8" sizey="12" userlevel="1" logparam="E52">
   <scaling name="Metric" units="Boost Target (bar absolute)" expression="x*.001333224" to_byte="x/.001333224" format="#0.000"/>
   <scaling name="Standard" units="Boost Target (psi relative sea level)" expression="(x-760)*.01933677" to_byte="(x/.01933677)+760" format="0.00"/>
   <table type="X Axis" name="Throttle Plate Opening Angle" storagetype="float" endian="little" logparam="E38">
    <scaling units="%" expression="x/.84" to_byte="x*.84" format="0.0" fineincrement=".3" coarseincrement="1" />
   </table>
   <table type="Y Axis" name="Engine Speed" storagetype="float" endian="little" logparam="P8">
    <scaling base="rpm"/>
   </table>
   <description>This map contains the desired boost targets. Boost compensation tables can impact the final boost target.</description>
  </table>

  <table base="Target Boost A" name="Target Boost B" >
   <description>This map is inherited from boost A, see boost A's description.</description>
  </table>
```

**Comment by dschultzca** [comment]
> Because currently, "Engine Speed (RPM)" as a unit in a "Engine Speed (RPM)" table name yields the following axis title "Engine Speed (RPM)(Engine Speed (RPM))".

This is under the user's control, so name the table, axis and units appropriately as not to repeat yourself.

**Comment by GTO2013** [comment]
Well currently I have had a lot of time to implement fresh new bugs in RomRaider :) I think it would make more sense to release a new public version for now and see which other bugs still needs fixing before other large changes are added

**Comment by dschultzca** [comment]
> Would iterating over the existing attributes help with this? Instead of unmarshallAttribute(node, name, default) it could use tableNode.getAttributes().item(i) in a loop to only set values which are actually defined.

Yes iterating over the attributes is the solution, but it is in the `public Scale unmarshallScale(Node scaleNode, Scale scale)`  method that we need to iterate over the `scale` element attributes to fix the problem.

**Comment by Pytrex** [comment]
@GTO2013 Good job with the fixes! :) Does the recent update allow for multiple scalingbases now? Or was it to fix the need for the format attribute? 

I can say that the scalingbase fix really slimmed down my definition file! It took quite a bit of time to do, even with search and replace, but it's well worth it.

**Comment by dschultzca** [comment]
The recent fix only addresses the format inheritance issue.  At the moment the only way to use multiple scales in a table is to  reiterate the name attribute in the table's `<scale>` element.
For example:
```
<scalingbase name="kph" expression="x*.6213712" to_byte="x/.6213712" units="kph" format="#" fineincrement="1" coarseincrement="5" />
<table ... >
  <scale base="kph" name="Metric" />
</table>
```
The scale will show up in the GUI in a table's scales list as "Metric" along with "Raw Value".  If you do not reiterate the name attribute, if will be forced to have the name "Default".


I'll be submitting a fix for this by adding a "category" attribute to the `scalingbase` element, so all you need to do is:
```
<scalingbase name="kph" category="Metric" expression="x*.6213712" to_byte="x/.6213712" units="kph" format="#" fineincrement="1" coarseincrement="5" />
<table ... >
  <scale base="kph" />
</table>
```
The "category" will be used to list the scaling options in the Table GUI.

**Comment by dschultzca** [comment]
scalingbase should now work correctly with multi-scales per table.
See the example definition: https://raw.githubusercontent.com/RomRaider/RomRaider/d791911f9458be1b8e0774329678c5871ca21e77/src/test/definitions/scalingbase_test.xml
The scale `name` attribute is reserved for use in only the `scalingbase` definition.  If you have used the `name` attribute in a `scaling` definition inside a `table`, change `name` to `category`.
