### ISSUE TITLE
Editor - Bitwise Switches Don't Properly Show Changed Status in Compare Window (Plus, Enhancement Idea)

### ISSUE THREAD

**Issue by Pytrex** [RomRaider/RomRaider#143]
In reference to https://github.com/RomRaider/RomRaider/commit/49797a1b82660e1fb095011c99d830171ed30caa

Bug;
When attempting to compare two bin files, bitwise switches don't show as changed. This isn't an issue for switches, however. So even if the bitwise switches have completely different values, the compare window shows them as being unchanged. 

Enhancement;
It would definitely be nice to have an option to JUST see the changed values, rather than the entire list of values, whether they're changed or not. While this isn't much of a concern for ROM's with smaller definition files, having to scroll through 2,000+ tables in a fixed size window isn't the easiest thing in the world haha

**Comment by GTO2013** [comment]
The entire BitwiseTables should be reworked anyway, they are the only table type that doesnt use DataCells internally. And it also saves its data in the GUI, which is not good. To make that work DataCells would need to have mask property instead of the table, so you can define set multiple DataCells at the same memory location with different masks. That would be the best solution imo because it reuses at lot of code if paired with the PresetManager.
The compare function would definitely benefit from better organization, I agree! A tab that shows the checksums inside the file with their current status would also be nice I think.

**Comment by GTO2013** [comment]
The Enhancement you mentioned is merged into master now, changed tables will be shown on top of the list now.

**Comment by Pytrex** [comment]
> The Enhancement you mentioned is merged into master now, changed tables will be shown on top of the list now.

Sweeeet! That'll make things MUCH easier haha
