### ISSUE TITLE
[Logger][Editor] Library Dependencies

### ISSUE THREAD

**Issue by GTO2013** [RomRaider/RomRaider#167]
Hi,
I went through the referenced libraries:

args4j-2.0.1.jar --> Parse cmd args,  not refenced in code. Remove?
cmu_time_awb.jar --> TTS
cmu_us_kal.jar --> TTS
cmudict04.jar --> TTS
cmulex.jar --> TTS
cmutimelex.jar --> TTS
com4j.jar --> MTS Plugin
en_us.jar --> TTS
freetts.jar --> TTS
Graph3D.jar --> Editor 3D View
j3dcore.jar --> Editor 3D View
j3dutils.jar --> Editor 3D View, are all 3 needed?
jama-1.0.2.jar --> Math library, I could not find references in code. Referenced by another jar?
jamlab.jar --> Cant find anything on this, whats it used for?
jcommon-1.0.12.jar --> Logger for drawing Dials and Graphs
jep.jar --> JEPUtil and BitWise for converting user defined formulas
jfreechart-1.0.9.jar -->  Logger for drawing Dials and Graphs
jna.jar --> Logger for J2534
jSerialComm-2.9.1 --> Logger for Serial Communication
log4j-1.2.14 --> Logging
phidget21.jar --> Logger: Phidget Plugin
platform.jar --> Seems to be part of jna.jar
vecmath.jar --> Math library, could not find any references to this, used by 3DGraph perhaps?

TTS is only used in PlainGaugeStyle.java in setWarning. I didnt even know about this feature. The question is it really needed? If yes, why not play a simple soundfile instead and remove the dependencies?

**Comment by dschultzca** [comment]
args4j is used by com4j.  
jamlab relies on jama and these are required by jep.  
vecmath and j3dutils are required by j3dcore.  
I don't know if there were plans to include more functionality from the freetts library, but it does seem to be a large dependency for such a limited use feature.  com4j can access the Micorsoft speak system but not for other OSs.

This is the tree from a few versions ago. rxtxcomm has since been replaced by jSerialComm and I removed jdic.
![deptree](https://user-images.githubusercontent.com/1688870/161384531-1c5dd64c-e218-4ac8-be7b-f97a12d62fb8.png)
