### ISSUE TITLE
Editor - Alphabetical Ordering

### ISSUE THREAD

**Issue by Pytrex** [RomRaider/RomRaider#187]
Potential Enhancement: Add a sorting attribute to the definition file's ROM ID section (base definition file where map data is stored rather than individual ROMs) to dictate whether categories and tables should be sorted alphabetically or whether they should be sorted based on order in the definition file. 
ex. 
```
	<romid>
		<xmlid>A2L</xmlid>
		<make>Nissan</make>
		<flashmethod>nisprog</flashmethod>
                <sorting>Automatic (Alphabetical)/Manual (Definition Order)</sorting>
	</romid>
```

Currently, it appears that both categories and tables will be automatically sorted alphabetically. While this makes sense for smaller definition files, it makes larger definition files more tedious to step through. It also causes 3D, 2D, and 1D parameters to be thrown all over the place due to it being based solely on alphabetical ordering regardless of parameter type.

**Comment by dschultzca** [comment]
For as long as RomRaider (and EcuFlash) has been in existence the table tree has always followed the order as defined in the definition.  After years of use, it does seem odd to me to have to look alphabetically for a category that I knew was at the beginning, or near the end of the list.  
Maybe this mode can be restored with an option for the user to select alphabetic listing.  I had to add a custom sort to the Table Compare menu to make the table list match the opened ROM listing, otherwise it was very difficult to locate a comparable table.  

BTW:  the name A2L is very misleading as an XMLID as RomRaider does not understand A2L syntax at all.

**Comment by dschultzca** [comment]
Added a sort option to the Editor settings, commit 82b0eb35be20c4fb2ddbe5765a18328e5c16dcd7.
