### ISSUE TITLE
Question: java syntax/api level?

### ISSUE THREAD

**Issue by rusefi** [RomRaider/RomRaider#68]
What is the official Java version for RomRaider?

I believe I've seen java 5.

What about Java 7? Java 8?

It's about very small things in my case - for instance can I use Objects.requireNotNull method?

**Comment by rusefi** [comment]
Update: I've just noticed target="1.6" source="1.6" in the build.xml

Is there a reason to still use 1.6 these days? Even java 7 is end of life already - https://java.com/en/download/faq/java_7.xml

My own opinion is probably to upgrade to 1.7 - not to upgrade to 1.8 yet.

**Comment by fredcooke** [comment]
There is zero point moving to Java 7 (not 1.7...) - if any move is to be made by Dale et al, then it should be directly to Java 8. Then again, the only reason you would do this is to upgrade the source, or begin the upgrade process, and having partially converted code is not ideal, however still the only way a project like this would move forward. Stay put or go to Java 8. Not 7.

**Comment by scotthew** [comment]
@rusefi I build/run with Java 8 on my dev machine.  If I remember right we have some issues with the 3rd party libraries being updated to Java 8 which is why we have not officially upgraded.  I did an update a while back to address some of these issues but cannot remember how far I got.  The 3D graphing library j3d comes to mind.

**Comment by fredcooke** [comment]
IIRC you're right, Scott. I know for a fact that it won't run on 64 bit Java, which is because there are no 64 bit binaries in the used libs. I can't remember what they are, but I did a lot of work towards formalising the dependency tree before abandoning it due to personal differences, and the dependency tree was quite messy and broad.

**Comment by rusefi** [comment]
@scotthew Something along the lines of http://www.romraider.com/forum/viewtopic.php?f=14&t=9758&start=30 ?

Google has purged https://code.google.com/p/graph3dj/

Sounds like the an issue for 3D migration is needed which java migration would depend on?

**Comment by rusefi** [comment]
@scotthew @fredcooke are we mixing java level (6-7-8-11) and bitness? graph3dj runs under java 8 32 bit just fine, same about compilation - things compile great with target="1.8" source="1.8"
